version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shoe-store-postgres
    environment:
      POSTGRES_USER: shoeuser
      POSTGRES_PASSWORD: shoepass
      POSTGRES_DB: shoestore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shoeuser -d shoestore"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shoe-store-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: